<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FactoryOptionSeeder extends Seeder
{
    public function run(): void
    {
        // Structure: category_name => [ group_name => [ [option_key, label, sub_label] ] ]
        // sub_label = null means direct option (no nesting)
        // sub_label = string means nested under that sub-label
        $data = [

            'Entertainment and Technology' => [
                'Audio System' => [
                    ['option_key' => 'auxiliaryaudioinput_bluetooth',        'label' => 'Bluetooth',                                    'sub_label' => 'Auxiliary audio input'],
                    ['option_key' => 'auxiliaryaudioinput_ipod',             'label' => 'IPod/iPhone',                                  'sub_label' => 'Auxiliary audio input'],
                    ['option_key' => 'auxiliaryaudioinput_jack',             'label' => 'Jack',                                         'sub_label' => 'Auxiliary audio input'],
                    ['option_key' => 'auxiliaryaudioinput_usb',              'label' => 'USB',                                          'sub_label' => 'Auxiliary audio input'],
                    ['option_key' => 'in-dashcd_singledisc',                 'label' => 'Single Disc In-Dash CD',                       'sub_label' => null],
                    ['option_key' => 'radio_amfm',                           'label' => 'AM/FM',                                        'sub_label' => 'Radio'],
                    ['option_key' => 'radio_hdradio',                        'label' => 'HD Radio',                                     'sub_label' => 'Radio'],
                    ['option_key' => 'radio_touchscreen',                    'label' => 'Touch Screen Display',                         'sub_label' => 'Radio'],
                    ['option_key' => 'radio_voiceoperated',                  'label' => 'Voice Operated',                               'sub_label' => 'Radio'],
                    ['option_key' => 'radiodatasystem',                      'label' => 'Radio data system',                            'sub_label' => null],
                    ['option_key' => 'radio_siriusxm',                       'label' => 'SiriusXM Satellite radio',                     'sub_label' => null],
                    ['option_key' => 'speedsensitivevolumecontrol',          'label' => 'Speed sensitive volume control',               'sub_label' => null],
                    ['option_key' => 'totalspeakers_6',                      'label' => '6',                                            'sub_label' => 'Total speakers'],
                    ['option_key' => 'totalspeakers_10',                     'label' => '10',                                           'sub_label' => 'Total speakers'],
                ],
                'Watts' => [
                    ['option_key' => 'watts_180',                            'label' => '180',                                          'sub_label' => null],
                    ['option_key' => 'watts_380',                            'label' => '380',                                          'sub_label' => null],
                    ['option_key' => 'watts_meridian_premium',               'label' => 'Meridian Premium brand',                       'sub_label' => null],
                    ['option_key' => 'watts_1_subwoofer',                    'label' => '1 Subwoofer',                                  'sub_label' => null],
                ],
                'In Car Entertainment' => [
                    ['option_key' => 'infotainment_entune',                  'label' => 'Entune Infotainment',                          'sub_label' => null],
                    ['option_key' => 'infotainment_app_marketplace',         'label' => 'App Marketplace Integration',                  'sub_label' => null],
                    ['option_key' => 'infotainment_pivi_pro',                'label' => 'PIVI Pro Infotainment',                        'sub_label' => null],
                    ['option_key' => 'infotainmentscreensize_61',            'label' => '6.1 In. Infotainment screen size',             'sub_label' => null],
                    ['option_key' => 'infotainmentscreensize_10',            'label' => '10 In. Infotainment screen size',              'sub_label' => null],
                ],
                'Smartphone integration' => [
                    ['option_key' => 'smartphone_android_auto',              'label' => 'Android Auto',                                 'sub_label' => null],
                    ['option_key' => 'smartphone_apple_carplay',             'label' => 'Apple CarPlay',                                'sub_label' => null],
                ],
                'Telematics' => [
                    ['option_key' => 'telematics_roadside_assistance',       'label' => 'Roadside Assistance Driver assistance app',    'sub_label' => null],
                    ['option_key' => 'electronicmessaging_voice',            'label' => 'Voice Operated',                               'sub_label' => 'Electronic messaging assistance'],
                    ['option_key' => 'electronicmessaging_read',             'label' => 'With Read Function',                           'sub_label' => 'Electronic messaging assistance'],
                    ['option_key' => 'hands-freephonecallintegration',       'label' => 'Voice Operated Hands-free phone call integration', 'sub_label' => null],
                    ['option_key' => 'wirelessdatalink_bluetooth',           'label' => 'Bluetooth Wireless data link',                 'sub_label' => null],
                ],
                'Voice Operated' => [
                    ['option_key' => 'voiceoperated_general',                'label' => 'Voice Operated',                               'sub_label' => null],
                    ['option_key' => 'voiceoperated_read_function',          'label' => 'With Read Function',                           'sub_label' => null],
                    ['option_key' => 'voiceoperated_handsfree',              'label' => 'Voice Operated Hands-free phone call integration', 'sub_label' => null],
                    ['option_key' => 'voiceoperated_realtime_traffic',       'label' => 'Real Time Traffic Navigation data',            'sub_label' => null],
                ],
                'Navigation system' => [
                    ['option_key' => 'navigation_memory_card',               'label' => 'Memory Card',                                  'sub_label' => null],
                    ['option_key' => 'navigation_touchscreen',               'label' => 'Touch Screen Display',                         'sub_label' => null],
                    ['option_key' => 'navigation_voiceoperated',             'label' => 'Voice Operated',                               'sub_label' => null],
                ],
                'Smart device app function' => [
                    ['option_key' => 'smartapp_engine_start',                'label' => 'Engine Start/cabin Preconditioning',           'sub_label' => null],
                    ['option_key' => 'smartapp_horn_light',                  'label' => 'Horn/light Operation',                         'sub_label' => null],
                    ['option_key' => 'smartapp_lock_operation',              'label' => 'Lock Operation',                               'sub_label' => null],
                    ['option_key' => 'smartapp_maintenance_status',          'label' => 'Maintenance Status',                           'sub_label' => null],
                    ['option_key' => 'smartapp_vehicle_location',            'label' => 'Vehicle Location',                             'sub_label' => null],
                    ['option_key' => 'smartapp_hotspot_wifi',                'label' => 'Hotspot Wi-Fi',                                'sub_label' => null],
                ],
            ],

            'Exterior' => [
                'Exterior Features' => [
                    ['option_key' => 'exhaust_dual_tip',                     'label' => 'Dual Tip Exhaust',                             'sub_label' => null],
                    ['option_key' => 'exhausttipcolor_stainless',            'label' => 'Stainless Steel',                              'sub_label' => 'Exhaust tip color'],
                    ['option_key' => 'exhausttipcolor_black',                'label' => 'Black',                                        'sub_label' => 'Exhaust tip color'],
                    ['option_key' => 'exhausttipcolor_chrome',               'label' => 'Chrome',                                       'sub_label' => 'Exhaust tip color'],
                    ['option_key' => 'grillecolor_black',                    'label' => 'Black Grille color',                           'sub_label' => null],
                    ['option_key' => 'roofline_rear_spoiler',                'label' => 'Roofline Rear spoiler',                        'sub_label' => null],
                    ['option_key' => 'rearliftgate_liftgate',                'label' => 'Liftgate',                                     'sub_label' => 'Rear trunk/liftgate'],
                    ['option_key' => 'rearliftgate_power_operated',          'label' => 'Power Operated',                               'sub_label' => 'Rear trunk/liftgate'],
                    ['option_key' => 'windowtrim_black',                     'label' => 'Black Window trim',                            'sub_label' => null],
                    ['option_key' => 'bodyside_moldings_black',              'label' => 'Black Body side moldings',                     'sub_label' => null],
                    ['option_key' => 'mudguards_front',                      'label' => 'Front',                                        'sub_label' => 'Mudguards'],
                    ['option_key' => 'mudguards_rear',                       'label' => 'Rear',                                         'sub_label' => 'Mudguards'],
                    ['option_key' => 'contrast_roof_paint',                  'label' => 'Contrast Roof Paint',                          'sub_label' => null],
                    ['option_key' => 'runningboardcolor_black',              'label' => 'Black',                                        'sub_label' => 'Running board color'],
                    ['option_key' => 'runningboardcolor_chrome',             'label' => 'Chrome',                                       'sub_label' => 'Running board color'],
                    ['option_key' => 'runningboards',                        'label' => 'Running boards',                               'sub_label' => null],
                ],
                'Lights' => [
                    ['option_key' => 'daytimerunninglights_led',             'label' => 'LED Daytime running lights',                   'sub_label' => null],
                    ['option_key' => 'exteriorentrylights_approach',         'label' => 'Approach Lamps',                               'sub_label' => 'Exterior entry lights'],
                    ['option_key' => 'exteriorentrylights_puddle',           'label' => 'Puddle Lamps',                                 'sub_label' => 'Exterior entry lights'],
                    ['option_key' => 'headlights_autodelayoff',              'label' => 'Auto Delay Off',                               'sub_label' => 'Headlights'],
                    ['option_key' => 'headlights_autohighbeam',              'label' => 'Auto High Beam Dimmer',                        'sub_label' => 'Headlights'],
                    ['option_key' => 'headlights_autoonoff',                 'label' => 'Auto On/off',                                  'sub_label' => 'Headlights'],
                    ['option_key' => 'headlights_led',                       'label' => 'LED',                                          'sub_label' => 'Headlights'],
                    ['option_key' => 'headlights_halogen',                   'label' => 'Halogen',                                      'sub_label' => 'Headlights'],
                    ['option_key' => 'headlights_selfleveling',              'label' => 'Self-leveling',                                'sub_label' => null],
                    ['option_key' => 'headlights_wiper_activated',           'label' => 'Wiper Activated',                              'sub_label' => null],
                    ['option_key' => 'rear_fog_lights',                      'label' => 'Rear fog lights',                              'sub_label' => null],
                    ['option_key' => 'taillights_led',                       'label' => 'LED Taillights',                               'sub_label' => null],
                    ['option_key' => 'front_fog_lights',                     'label' => 'Front fog lights',                             'sub_label' => null],
                    ['option_key' => 'headlight_cleaners',                   'label' => 'Headlight cleaners',                           'sub_label' => null],
                ],
                'Mirrors' => [
                    ['option_key' => 'sidemirror_power',                     'label' => 'Power',                                        'sub_label' => 'Side mirror adjustments'],
                    ['option_key' => 'sidemirror_power_folding',             'label' => 'Power Folding',                                'sub_label' => 'Side mirror adjustments'],
                    ['option_key' => 'sidemirror_reverse_gear_tilt',         'label' => 'Reverse Gear Tilt',                            'sub_label' => 'Side mirror adjustments'],
                    ['option_key' => 'sidemirror_manualfolding',             'label' => 'Manual Folding',                               'sub_label' => 'Side mirror adjustments'],
                    ['option_key' => 'sidemirrors_autodimming',              'label' => 'Auto-dimming',                                 'sub_label' => 'Side mirrors'],
                    ['option_key' => 'sidemirrors_heated',                   'label' => 'Heated',                                       'sub_label' => 'Side mirrors'],
                ],
                'Wheels and Tires' => [
                    ['option_key' => 'sparetiresize_temporary',              'label' => 'Temporary',                                    'sub_label' => 'Spare tire size'],
                    ['option_key' => 'sparetiresize_fullsize',               'label' => 'Full-size',                                    'sub_label' => 'Spare tire size'],
                    ['option_key' => 'sparewheeltype_steel',                 'label' => 'Steel',                                        'sub_label' => 'Spare wheel type'],
                    ['option_key' => 'sparewheeltype_aluminum',              'label' => 'Aluminum Alloy',                               'sub_label' => 'Spare wheel type'],
                    ['option_key' => 'tirepressuremonitoringsystem',         'label' => 'Tire Pressure Monitoring System',              'sub_label' => null],
                    ['option_key' => 'wheels_aluminum_alloy',                'label' => 'Aluminum Alloy',                               'sub_label' => 'Wheels'],
                    ['option_key' => 'wheels_paintedaluminum',               'label' => 'Painted Aluminum Alloy',                       'sub_label' => 'Wheels'],
                    ['option_key' => 'wheels_steel',                         'label' => 'Steel',                                        'sub_label' => 'Wheels'],
                    ['option_key' => 'wheellocks_frontandrear',              'label' => 'Front And Rear',                               'sub_label' => 'Wheel locks'],
                    ['option_key' => 'wheellocks_spareonly',                 'label' => 'Spare Only',                                   'sub_label' => 'Wheel locks'],
                ],
                'Windows' => [
                    ['option_key' => 'frontwipers_rain_sensing',             'label' => 'Rain Sensing',                                 'sub_label' => 'Front wipers'],
                    ['option_key' => 'frontwipers_speed_sensitive',          'label' => 'Speed Sensitive',                              'sub_label' => 'Front wipers'],
                    ['option_key' => 'frontwipers_variable_intermittent',    'label' => 'Variable Intermittent',                        'sub_label' => 'Front wipers'],
                    ['option_key' => 'windshield_infrared_laminated',        'label' => 'Infrared-reflecting Windshield Laminated glass', 'sub_label' => null],
                    ['option_key' => 'liftgate_window_fixed',                'label' => 'Fixed Liftgate window',                        'sub_label' => null],
                    ['option_key' => 'powerwindows_remotely_operated',       'label' => 'Remotely Operated',                            'sub_label' => 'Power windows'],
                    ['option_key' => 'powerwindows_safety_reverse',          'label' => 'Safety Reverse',                               'sub_label' => 'Power windows'],
                    ['option_key' => 'rearprivacyglass',                     'label' => 'Rear privacy glass',                           'sub_label' => null],
                    ['option_key' => 'rearwiper_auto_on_reverse',            'label' => 'Auto-on In Reverse',                           'sub_label' => 'Rear wiper'],
                    ['option_key' => 'rearwiper_variable_intermittent',      'label' => 'Variable Intermittent',                        'sub_label' => 'Rear wiper'],
                    ['option_key' => 'rearwiper_with_washer',                'label' => 'With Washer',                                  'sub_label' => 'Rear wiper'],
                    ['option_key' => 'glass_solar_tinted',                   'label' => 'Solar-tinted glass',                           'sub_label' => null],
                    ['option_key' => 'rear_window_defogger',                 'label' => 'Rear Window defogger',                         'sub_label' => null],
                    ['option_key' => 'windshield_heated',                    'label' => 'Heated windshield',                            'sub_label' => null],
                    ['option_key' => 'pickupslidingrearwindow_manual',       'label' => 'Manual Pickup sliding rear window',            'sub_label' => null],
                ],
                'Roof' => [
                    ['option_key' => 'moonroof_anti_trapping',               'label' => 'Anti-trapping',                                'sub_label' => 'Moonroof / Sunroof'],
                    ['option_key' => 'moonroof_one_touch',                   'label' => 'One-touch Open/close',                         'sub_label' => 'Moonroof / Sunroof'],
                    ['option_key' => 'moonroof_panoramic',                   'label' => 'Panoramic',                                    'sub_label' => 'Moonroof / Sunroof'],
                    ['option_key' => 'moonroof_power_sunshade',              'label' => 'Power Sunshade',                               'sub_label' => 'Moonroof / Sunroof'],
                    ['option_key' => 'moonroof_tilt_slide',                  'label' => 'Tilt/slide',                                   'sub_label' => 'Moonroof / Sunroof'],
                    ['option_key' => 'roof_rails_black',                     'label' => 'Black Roof rails',                             'sub_label' => null],
                ],
            ],

            'Interior' => [
                'Air Conditioning' => [
                    ['option_key' => 'airfiltration',                        'label' => 'Air filtration',                               'sub_label' => null],
                    ['option_key' => 'airfiltration_ionizing',               'label' => 'Ionizing',                                     'sub_label' => 'Air filtration'],
                    ['option_key' => 'frontairconditioning_automatic',       'label' => 'Automatic Climate Control Front air conditioning', 'sub_label' => null],
                    ['option_key' => 'frontairconditioningzones_dual',       'label' => 'Dual Front air conditioning zones',            'sub_label' => null],
                    ['option_key' => 'frontairconditioning',                 'label' => 'Front air conditioning',                       'sub_label' => null],
                    ['option_key' => 'frontairconditioningzones_single',     'label' => 'Single Front air conditioning zones',          'sub_label' => null],
                    ['option_key' => 'rearvents_second_row',                 'label' => 'Second Row',                                   'sub_label' => 'Rear vents'],
                    ['option_key' => 'rearvents_third_row',                  'label' => 'Third Row',                                    'sub_label' => 'Rear vents'],
                    ['option_key' => 'humidity_dewpoint_sensors',            'label' => 'Humidity/dewpoint sensors',                    'sub_label' => null],
                    ['option_key' => 'rearairconditioning_automatic',        'label' => 'Automatic Climate Control',                    'sub_label' => 'Rear air conditioning'],
                    ['option_key' => 'rearairconditioning_independent',       'label' => 'Independently Controlled',                     'sub_label' => 'Rear air conditioning'],
                    ['option_key' => 'rearairconditioning_zones_dual',       'label' => 'Dual Rear air conditioning zones',             'sub_label' => null],
                ],
                'Comfort Features' => [
                    ['option_key' => 'armrests_rear_center_cupholders',      'label' => 'Rear Center With Cupholders',                  'sub_label' => 'Armrests'],
                    ['option_key' => 'armrests_rear_folding',                'label' => 'Rear Folding',                                 'sub_label' => 'Armrests'],
                    ['option_key' => 'centerconsoletrim_aluminum',           'label' => 'Aluminum',                                     'sub_label' => 'Center console trim'],
                    ['option_key' => 'centerconsoletrim_leather',            'label' => 'Leather',                                      'sub_label' => 'Center console trim'],
                    ['option_key' => 'dashtrim_leatherette',                 'label' => 'Leatherette Dash trim',                        'sub_label' => null],
                    ['option_key' => 'doorsilltrim_aluminum',                'label' => 'Aluminum',                                     'sub_label' => 'Door sill trim'],
                    ['option_key' => 'doorsilltrim_illuminated_scuff',       'label' => 'Illuminated Scuff Plate',                      'sub_label' => 'Door sill trim'],
                    ['option_key' => 'doorsilltrim_scuffplate',              'label' => 'Scuff Plate Door sill trim',                   'sub_label' => null],
                    ['option_key' => 'doortrim_leatherette',                 'label' => 'Leatherette Door trim',                        'sub_label' => null],
                    ['option_key' => 'floormatmaterial_carpet',              'label' => 'Carpet',                                       'sub_label' => 'Floor mat material'],
                    ['option_key' => 'floormatmaterial_rubber',              'label' => 'Rubber/vinyl',                                 'sub_label' => 'Floor mat material'],
                    ['option_key' => 'floormaterial_carpet',                 'label' => 'Carpet Floor material',                        'sub_label' => null],
                    ['option_key' => 'floormats_front',                      'label' => 'Front',                                        'sub_label' => 'Floor mats'],
                    ['option_key' => 'floormats_rear',                       'label' => 'Rear',                                         'sub_label' => 'Floor mats'],
                    ['option_key' => 'footpedaltrim_alloy',                  'label' => 'Alloy Foot pedal trim',                        'sub_label' => null],
                    ['option_key' => 'interioraccents_aluminum',             'label' => 'Aluminum',                                     'sub_label' => 'Interior accents'],
                    ['option_key' => 'interioraccents_metallic',             'label' => 'Metallic-tone',                                'sub_label' => 'Interior accents'],
                    ['option_key' => 'interioraccents_veneer',               'label' => 'Veneer',                                       'sub_label' => 'Interior accents'],
                    ['option_key' => 'interioraccents_wood',                 'label' => 'Wood',                                         'sub_label' => 'Interior accents'],
                    ['option_key' => 'shiftknobtrim_aluminum',               'label' => 'Aluminum Shift knob trim',                     'sub_label' => null],
                    ['option_key' => 'steeringwheeltrim_alloy',              'label' => 'Alloy',                                        'sub_label' => 'Steering wheel trim'],
                    ['option_key' => 'steeringwheeltrim_leather',            'label' => 'Leather',                                      'sub_label' => 'Steering wheel trim'],
                    ['option_key' => 'steeringwheeltrim_faux_suede',         'label' => 'Faux Suede',                                   'sub_label' => 'Steering wheel trim'],
                    ['option_key' => 'cargoareafloormat_rubber',             'label' => 'Rubber/vinyl Cargo area floor mat',            'sub_label' => null],
                ],
                'Convenience Features' => [
                    ['option_key' => 'heated_steering_wheel',                'label' => 'Heated steering wheel',                        'sub_label' => null],
                    ['option_key' => 'ambientlighting',                      'label' => 'Ambient lighting',                             'sub_label' => null],
                    ['option_key' => 'ambientlighting_color_adjustable',     'label' => 'Color-adjustable',                             'sub_label' => 'Ambient lighting'],
                    ['option_key' => 'cargo_area_light',                     'label' => 'Cargo area light',                             'sub_label' => null],
                    ['option_key' => 'centerconsole_frontarmrest',           'label' => 'Front Console With Armrest And Storage Center console', 'sub_label' => null],
                    ['option_key' => 'door_courtesy_lights',                 'label' => 'Door Courtesy lights',                         'sub_label' => null],
                    ['option_key' => 'cruise_control',                       'label' => 'Cruise control',                               'sub_label' => null],
                    ['option_key' => 'cupholders_front',                     'label' => 'Front',                                        'sub_label' => 'Cupholders'],
                    ['option_key' => 'cupholders_rear',                      'label' => 'Rear',                                         'sub_label' => 'Cupholders'],
                    ['option_key' => 'footwelllights',                       'label' => 'Footwell lights',                              'sub_label' => null],
                    ['option_key' => 'footwelllights_color_adjustable',    'label' => 'Color-adjustable',                             'sub_label' => 'Footwell lights'],
                    ['option_key' => 'multifunction_remote_keyless',         'label' => 'Keyless Entry',                                'sub_label' => 'Multi-function remote'],
                    ['option_key' => 'multifunction_remote_panic',           'label' => 'Panic Alarm',                                  'sub_label' => 'Multi-function remote'],
                    ['option_key' => 'multifunction_remote_trunk',           'label' => 'Trunk Release',                                'sub_label' => 'Multi-function remote'],
                    ['option_key' => 'multifunction_remote_proximity',       'label' => 'Proximity Entry System',                       'sub_label' => 'Multi-function remote'],
                    ['option_key' => 'one-touchwindows_4',                   'label' => '4 One-touch windows',                          'sub_label' => null],
                    ['option_key' => 'one-touchwindows',                     'label' => '1 One-touch windows',                          'sub_label' => null],
                    ['option_key' => 'overheadconsole_front',                'label' => 'Front Overhead console',                       'sub_label' => null],
                    ['option_key' => 'poweroutlets_12v_cargo',               'label' => '12V Cargo Area',                               'sub_label' => 'Power outlet(s)'],
                    ['option_key' => 'poweroutlets_12v_front',               'label' => '12V Front',                                    'sub_label' => 'Power outlet(s)'],
                    ['option_key' => 'poweroutlets_12v_rear',               'label' => '12V Rear',                                     'sub_label' => 'Power outlet(s)'],
                    ['option_key' => 'poweroutlets_usb_front',             'label' => 'USB Front',                                    'sub_label' => 'Power outlet(s)'],
                    ['option_key' => 'poweroutlets_12v',                     'label' => '12V Front Power outlet(s)',                    'sub_label' => null],
                    ['option_key' => 'poweroutlets_usbc_front',              'label' => 'USB-C Front',                                  'sub_label' => null],
                    ['option_key' => 'powersteering_variable',               'label' => 'Variable/speed-proportional Power steering',   'sub_label' => null],
                    ['option_key' => 'push_button_start',                    'label' => 'Push-button start',                            'sub_label' => null],
                    ['option_key' => 'readinglights_front',                  'label' => 'Front',                                        'sub_label' => 'Reading lights'],
                    ['option_key' => 'readinglights_rear',                   'label' => 'Rear',                                         'sub_label' => 'Reading lights'],
                    ['option_key' => 'rearviewmirror_autodimming',           'label' => 'Auto-dimming',                                 'sub_label' => 'Rearview mirror'],
                    ['option_key' => 'rearviewmirror_camera',                'label' => 'Camera-based',                                 'sub_label' => 'Rearview mirror'],
                    ['option_key' => 'rearviewmirror_manual',                'label' => 'Manual Day/night Rearview mirror',             'sub_label' => null],
                    ['option_key' => 'steeringwheel_tilttelescopic',         'label' => 'Tilt And Telescopic Steering wheel',           'sub_label' => null],
                    ['option_key' => 'steeringwheelcontrols_audio',          'label' => 'Audio',                                        'sub_label' => 'Steering wheel mounted controls'],
                    ['option_key' => 'steeringwheelcontrols_cruise',         'label' => 'Cruise Control',                               'sub_label' => 'Steering wheel mounted controls'],
                    ['option_key' => 'steeringwheelcontrols_multi',          'label' => 'Multi-function',                               'sub_label' => 'Steering wheel mounted controls'],
                    ['option_key' => 'steeringwheelcontrols_paddle',         'label' => 'Paddle Shifter',                               'sub_label' => 'Steering wheel mounted controls'],
                    ['option_key' => 'steeringwheelcontrols_phone',          'label' => 'Phone',                                        'sub_label' => 'Steering wheel mounted controls'],
                    ['option_key' => 'steeringwheelcontrols_voice',          'label' => 'Voice Control',                                'sub_label' => 'Steering wheel mounted controls'],
                    ['option_key' => 'homelink_garage_door',                 'label' => 'Homelink - Garage Door Opener Universal remote transmitter', 'sub_label' => null],
                    ['option_key' => 'vanity_mirrors_dual_illuminating',     'label' => 'Dual Illuminating Vanity mirrors',             'sub_label' => null],
                    ['option_key' => 'ashtray',                              'label' => 'Ashtray',                                      'sub_label' => null],
                ],
                'Instrumentation' => [
                    ['option_key' => 'adaptivecruisecontrol',                'label' => 'Adaptive cruise control',                      'sub_label' => null],
                    ['option_key' => 'windshield_sunshade',                  'label' => 'Windshield Sunshade',                          'sub_label' => null],
                    ['option_key' => 'wireless_charging_front',              'label' => 'Front Wireless charging station',              'sub_label' => null],
                    ['option_key' => 'wristband_vehicle_access',             'label' => 'Wristband vehicle access',                     'sub_label' => null],
                    ['option_key' => 'compass',                              'label' => 'Compass',                                      'sub_label' => null],
                    ['option_key' => 'externaltemperaturedisplay',           'label' => 'External temperature display',                 'sub_label' => null],
                    ['option_key' => 'fueleconomydisplay_mpg',               'label' => 'MPG',                                          'sub_label' => 'Fuel economy display'],
                    ['option_key' => 'fueleconomydisplay_range',             'label' => 'Range',                                        'sub_label' => 'Fuel economy display'],
                    ['option_key' => 'gauge_tachometer',                     'label' => 'Tachometer Gauge',                             'sub_label' => null],
                    ['option_key' => 'instrumentclusterscreensize_7',        'label' => '7 In.',                                        'sub_label' => 'Instrument cluster screen size'],
                    ['option_key' => 'instrumentclusterscreensize_123',      'label' => '12.3 In.',                                     'sub_label' => 'Instrument cluster screen size'],
                    ['option_key' => 'instrumentclusterscreensize',          'label' => '4.2 In. Instrument cluster screen size',       'sub_label' => null],
                    ['option_key' => 'multi-functiondisplay',                'label' => 'Multi-function display',                       'sub_label' => null],
                    ['option_key' => 'instrumentcluster_customizable',       'label' => 'Customizable instrument cluster',              'sub_label' => null],
                    ['option_key' => 'head_up_display',                      'label' => 'Head-up display',                              'sub_label' => null],
                ],
                'Seats' => [
                    ['option_key' => 'driverseat_power_12',                  'label' => '12',                                           'sub_label' => 'Driver seat power adjustments'],
                    ['option_key' => 'driverseat_power_lumbar',              'label' => '4-way Power Lumbar',                           'sub_label' => 'Driver seat power adjustments'],
                    ['option_key' => 'driverseat_power_height',              'label' => 'Height',                                       'sub_label' => 'Driver seat power adjustments'],
                    ['option_key' => 'driverseat_power_reclining',           'label' => 'Reclining',                                    'sub_label' => 'Driver seat power adjustments'],
                    ['option_key' => 'frontseattype_bucket',                 'label' => 'Bucket Front seat',                            'sub_label' => null],
                    ['option_key' => 'passengerseat_power_12',             'label' => '12',                                           'sub_label' => 'Passenger seat power adjustments'],
                    ['option_key' => 'passengerseat_power_lumbar',           'label' => '4-way Power Lumbar',                           'sub_label' => 'Passenger seat power adjustments'],
                    ['option_key' => 'passengerseat_power_height',           'label' => 'Height',                                       'sub_label' => 'Passenger seat power adjustments'],
                    ['option_key' => 'passengerseat_power_reclining',        'label' => 'Reclining',                                    'sub_label' => 'Passenger seat power adjustments'],
                    ['option_key' => 'rearseat_sliding',                     'label' => 'Sliding',                                      'sub_label' => 'Rear seat'],
                    ['option_key' => 'rearseat_heated',                      'label' => 'Heated',                                       'sub_label' => 'Rear seat'],
                    ['option_key' => 'rearseatfolding_split',                'label' => 'Split Rear seat folding',                      'sub_label' => null],
                    ['option_key' => 'rearseatfolding_foldsup',              'label' => 'Folds Up Rear seat folding',                   'sub_label' => null],
                    ['option_key' => 'rearseat_manual_reclining',            'label' => 'Reclining Rear seat manual adjustments',       'sub_label' => null],
                    ['option_key' => 'rearseat_6040_split_bench',            'label' => '60-40 Split Bench Rear seat',                  'sub_label' => null],
                    ['option_key' => 'rearseattype_jumpseats',               'label' => 'Jumpseats Rear seat',                          'sub_label' => null],
                    ['option_key' => 'upholstery_leather',                   'label' => 'Leather Upholstery',                           'sub_label' => null],
                    ['option_key' => 'upholstery_cloth',                     'label' => 'Cloth Upholstery',                             'sub_label' => null],
                    ['option_key' => 'upholsteryaccents_contrast_stitching', 'label' => 'Contrast Stitching',                           'sub_label' => 'Upholstery accents'],
                    ['option_key' => 'upholsteryaccents_perforated',         'label' => 'Perforated',                                   'sub_label' => 'Upholstery accents'],
                    ['option_key' => 'heated_driver_seat',                   'label' => 'Heated Driver seat',                           'sub_label' => null],
                    ['option_key' => 'heated_passenger_seat',              'label' => 'Heated Passenger seat',                        'sub_label' => null],
                    ['option_key' => 'thirdrowseatfolding_flat',             'label' => 'Flat',                                         'sub_label' => 'Third row seat folding'],
                    ['option_key' => 'thirdrowseatfolding_split',            'label' => 'Split',                                        'sub_label' => 'Third row seat folding'],
                    ['option_key' => 'thirdrowseat_5050_split_bench',        'label' => '50-50 Split Bench Third row seat',             'sub_label' => null],
                ],
            ],

            'Performance' => [
                'Powertrain' => [
                    ['option_key' => 'drivetrain_fulltime_4wd',              'label' => 'Full Time 4WD',                                'sub_label' => null],
                    ['option_key' => 'autostart_stop',                       'label' => 'Auto start/stop',                              'sub_label' => null],
                    ['option_key' => 'batterysaver',                         'label' => 'Battery saver',                                'sub_label' => null],
                    ['option_key' => 'drive_mode_selector',                  'label' => 'Drive mode selector',                          'sub_label' => null],
                ],
                'Suspension' => [
                    ['option_key' => 'frontstabilizerbar',                   'label' => 'Front stabilizer bar',                         'sub_label' => null],
                    ['option_key' => 'frontstabilizerbar_30mm',              'label' => 'Diameter 30 Mm Front stabilizer bar',          'sub_label' => null],
                    ['option_key' => 'frontstruts_macpherson',               'label' => 'MacPherson Front struts',                      'sub_label' => null],
                    ['option_key' => 'frontstruts',                          'label' => 'Front struts',                                 'sub_label' => null],
                    ['option_key' => 'frontsuspensionclassification',        'label' => 'Independent Front suspension classification',  'sub_label' => null],
                    ['option_key' => 'frontsuspensiontype_doublewishbone',   'label' => 'Double Wishbone Front suspension',             'sub_label' => null],
                    ['option_key' => 'rearstabilizerbar',                    'label' => 'Rear stabilizer bar',                          'sub_label' => null],
                    ['option_key' => 'rearsuspensionclassification_independent', 'label' => 'Independent Rear suspension classification', 'sub_label' => null],
                    ['option_key' => 'rearsuspensionclassification',         'label' => 'Solid Live Axle Rear suspension classification', 'sub_label' => null],
                    ['option_key' => 'rearsuspension_multilink',             'label' => 'Multi-link Rear suspension',                   'sub_label' => null],
                    ['option_key' => 'suspension_active',                    'label' => 'Active suspension',                            'sub_label' => null],
                    ['option_key' => 'suspension_ride_control',              'label' => 'Ride Control Driver adjustable suspension',    'sub_label' => null],
                    ['option_key' => 'suspension_self_leveling',             'label' => 'Self leveling suspension',                     'sub_label' => null],
                    ['option_key' => 'suspension_electronic_control',        'label' => 'Electronic Suspension control',                'sub_label' => null],
                ],
                'Towing and Hauling' => [
                    ['option_key' => 'towhooks_front',                       'label' => 'Front',                                        'sub_label' => 'Tow hooks'],
                    ['option_key' => 'towhooks_rear',                        'label' => 'Rear',                                         'sub_label' => 'Tow hooks'],
                    ['option_key' => 'trailer_backup_steering',              'label' => 'Straight Line And Turning Automated trailer backup steering', 'sub_label' => null],
                    ['option_key' => 'trailer_hitch_receiver',               'label' => 'Receiver Hitch Trailer hitch',                 'sub_label' => null],
                    ['option_key' => 'pickupbedcargo_tiedown',               'label' => 'Tie-down Anchors Pickup bed cargo management', 'sub_label' => null],
                ],
            ],

            'Safety and Security' => [
                'Airbags' => [
                    ['option_key' => 'airbagdeactivation_occupant',          'label' => 'Occupant Sensing Passenger Airbag deactivation','sub_label' => null],
                    ['option_key' => 'frontairbags_dual',                    'label' => 'Dual Front airbags',                           'sub_label' => null],
                    ['option_key' => 'kneeairbags_dualfront',                'label' => 'Dual Front Knee airbags',                      'sub_label' => null],
                    ['option_key' => 'sideairbags_front',                    'label' => 'Front Side airbags',                           'sub_label' => null],
                    ['option_key' => 'sidecurtainairbags_front',             'label' => 'Front',                                        'sub_label' => 'Side curtain airbags'],
                    ['option_key' => 'sidecurtainairbags_rear',              'label' => 'Rear',                                         'sub_label' => 'Side curtain airbags'],
                ],
                'Brakes' => [
                    ['option_key' => 'abs_4wheel',                           'label' => '4-wheel ABS',                                  'sub_label' => null],
                    ['option_key' => 'brakingassist',                        'label' => 'Braking assist',                               'sub_label' => null],
                    ['option_key' => 'electronicbrakeforcedistribution',     'label' => 'Electronic brakeforce distribution',           'sub_label' => null],
                    ['option_key' => 'frontbraketype_ventilateddisc',        'label' => 'Ventilated Disc Front brake',                  'sub_label' => null],
                    ['option_key' => 'powerbrakes',                          'label' => 'Power brakes',                                 'sub_label' => null],
                    ['option_key' => 'rearbraketype_drum',                   'label' => 'Drum Rear brake',                              'sub_label' => null],
                ],
                'Safety' => [
                    ['option_key' => 'activeheadrestraints_dualfront',       'label' => 'Dual Front Active head restraints',            'sub_label' => null],
                    ['option_key' => 'automaticemergencybraking_front',      'label' => 'Front',                                        'sub_label' => 'Automatic emergency braking'],
                    ['option_key' => 'automaticemergencybraking_pedestrian', 'label' => 'Front Pedestrian',                             'sub_label' => 'Automatic emergency braking'],
                    ['option_key' => 'camerasystem_rearview',                'label' => 'Rearview Camera system',                       'sub_label' => null],
                    ['option_key' => 'childseatanchors_latch',               'label' => 'LATCH System Child seat anchors',              'sub_label' => null],
                    ['option_key' => 'impactsensor_fuelcutoff',              'label' => 'Fuel Cut-off Impact sensor',                   'sub_label' => null],
                    ['option_key' => 'lanedeviationsensors',                 'label' => 'Lane deviation sensors',                       'sub_label' => null],
                    ['option_key' => 'precollisionwarning_audible',          'label' => 'Audible Warning',                              'sub_label' => 'Pre-collision warning system'],
                    ['option_key' => 'precollisionwarning_pedestrian',       'label' => 'Pedestrian Detection',                         'sub_label' => 'Pre-collision warning system'],
                    ['option_key' => 'precollisionwarning_visual',           'label' => 'Visual Warning',                               'sub_label' => 'Pre-collision warning system'],
                    ['option_key' => 'rearviewmonitor_indash',               'label' => 'In Dash Rearview monitor',                     'sub_label' => null],
                    ['option_key' => 'firstaidkit',                          'label' => 'First aid kit',                                'sub_label' => null],
                ],
                'Seatbelts' => [
                    ['option_key' => 'emergencylockingretractors_front',     'label' => 'Front',                                        'sub_label' => 'Emergency locking retractors'],
                    ['option_key' => 'emergencylockingretractors_rear',      'label' => 'Rear',                                         'sub_label' => 'Emergency locking retractors'],
                    ['option_key' => 'seatbeltforcelimiters_front',          'label' => 'Front Seatbelt force limiters',                'sub_label' => null],
                    ['option_key' => 'seatbeltpretensioners_front',          'label' => 'Front Seatbelt pretensioners',                 'sub_label' => null],
                    ['option_key' => 'seatbeltwarningsensor_front',          'label' => 'Front Seatbelt warning sensor',                'sub_label' => null],
                ],
                'Security' => [
                    ['option_key' => 'antitheft_immobilizer',                'label' => 'Vehicle Immobilizer',                          'sub_label' => 'Anti-theft system'],
                    ['option_key' => 'antitheft_alarm',                      'label' => 'Alarm',                                        'sub_label' => 'Anti-theft system'],
                    ['option_key' => 'antitheft_glassbreakage',              'label' => 'Glass Breakage Sensor',                        'sub_label' => 'Anti-theft system'],
                    ['option_key' => 'powerdoorlocks_autolocking',           'label' => 'Auto-locking Power door locks',                'sub_label' => null],
                ],
                'Stability and Traction' => [
                    ['option_key' => 'hillholdercontrol',                    'label' => 'Hill holder control',                          'sub_label' => null],
                    ['option_key' => 'stabilitycontrol',                     'label' => 'Stability control',                            'sub_label' => null],
                    ['option_key' => 'tractioncontrol',                      'label' => 'Traction control',                             'sub_label' => null],
                ],
            ],
        ];

        foreach ($data as $categoryName => $groups) {
            $category = DB::table('factory_option_categories')
                ->where('name', $categoryName)
                ->first();

            if (!$category) continue;

            foreach ($groups as $groupName => $options) {
                $group = DB::table('factory_option_groups')
                    ->where('name', $groupName)
                    ->where('category_id', $category->id)
                    ->first();

                foreach ($options as $option) {
                    DB::table('factory_options')->insertOrIgnore([
                        'category_id' => $category->id,
                        'group_id'    => $group?->id,
                        'option_key'  => $option['option_key'],
                        'label'       => $option['label'],
                        'sub_label'   => $option['sub_label'],
                        'created_at'  => now(),
                        'updated_at'  => now(),
                    ]);
                }
            }
        }
    }
}